services:
  flask_app:
    build: .
    container_name: pdd-express
    restart: unless-stopped
    ports:
      - "15000:5000"
    env_file:
      - .env
    volumes:
      - /home/service/pdd-express/pdd.db:/app/pdd.db
      - /home/service/pdd-express/logs:/app/logs
      - /home/service/pdd-express/.env:/app/.env
      - /home/service/pdd-express/src:/app/src
    command: sh -c "python src/init_db.py && python src/main.py"
